kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - push

workspace:
  path: "/mos" # http://plugins.drone.io/drone-plugins/drone-docker/

steps:
  - name: Build Images
    image: plugins/docker
    settings:
      repo: macbury/mos
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
